// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPq2muZIbykcE91lCKeLRqm_69uDEWnM',
    appId: '1:502647647322:web:b1d7be2ddb55b1124b7c63',
    messagingSenderId: '502647647322',
    projectId: 'lockin-smart-study',
    authDomain: 'lockin-smart-study.firebaseapp.com',
    storageBucket: 'lockin-smart-study.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaG7K8_qvVKxqyNzSXkZoNPs-On6MUYM0',
    appId: '1:502647647322:android:695c7570d547f3494b7c63',
    messagingSenderId: '502647647322',
    projectId: 'lockin-smart-study',
    storageBucket: 'lockin-smart-study.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfttOc9mMmXEcbUzLSOKNo9tQf3TD7tQg',
    appId: '1:502647647322:ios:674f9373e1e0f77c4b7c63',
    messagingSenderId: '502647647322',
    projectId: 'lockin-smart-study',
    storageBucket: 'lockin-smart-study.firebasestorage.app',
    androidClientId: '502647647322-6iuigd5o1mm9lr66mggf3qj574r8rvp1.apps.googleusercontent.com',
    iosClientId: '502647647322-99tlhkj12rlbvgkhupcin43rslhs1bo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfttOc9mMmXEcbUzLSOKNo9tQf3TD7tQg',
    appId: '1:502647647322:ios:674f9373e1e0f77c4b7c63',
    messagingSenderId: '502647647322',
    projectId: 'lockin-smart-study',
    storageBucket: 'lockin-smart-study.firebasestorage.app',
    androidClientId: '502647647322-6iuigd5o1mm9lr66mggf3qj574r8rvp1.apps.googleusercontent.com',
    iosClientId: '502647647322-99tlhkj12rlbvgkhupcin43rslhs1bo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfPq2muZIbykcE91lCKeLRqm_69uDEWnM',
    appId: '1:502647647322:web:8b92b0d22dce83794b7c63',
    messagingSenderId: '502647647322',
    projectId: 'lockin-smart-study',
    authDomain: 'lockin-smart-study.firebaseapp.com',
    storageBucket: 'lockin-smart-study.firebasestorage.app',
  );
}
